import asyncio
import os
import asyncpg
from typing import List, Dict, Any

# Categorías asumiendo el orden en init.sql:
# 1: animales, 2: alimentos, 3: partes_del_cuerpo, 4: familia, 5: objetos_del_hogar,
# 6: juguetes, 7: ropa, 8: colores_y_formas, 9: verbos, 10: emociones,
# 11: naturaleza_y_ciencia, 12: profesiones, 13: lugares, 14: lenguaje_figurado,
# 15: transporte, 16: conceptos_abstractos

RECURSOS_SEED: List[Dict[str, Any]] = [
    {'id': 'W_001', 'texto': 'Perro', 'nivel': 1, 'fonema': 'p', 'cat': 2, 'dif': 'baja', 'img': 'perro', 'tags': []},
    {'id': 'W_002', 'texto': 'Gato', 'nivel': 1, 'fonema': 't', 'cat': 3, 'dif': 'baja', 'img': 'gato', 'tags': []},
    {'id': 'W_003', 'texto': 'Vaca', 'nivel': 1, 'fonema': 'v', 'cat': 4, 'dif': 'baja', 'img': 'vaca', 'tags': []},
    {'id': 'W_004', 'texto': 'Pato', 'nivel': 1, 'fonema': 'p', 'cat': 5, 'dif': 'baja', 'img': 'pato', 'tags': []},
    {'id': 'W_005', 'texto': 'Pez', 'nivel': 1, 'fonema': 'p', 'cat': 6, 'dif': 'baja', 'img': 'pez', 'tags': []},
    {'id': 'W_006', 'texto': 'Mano', 'nivel': 1, 'fonema': 'm', 'cat': 7, 'dif': 'baja', 'img': 'mano', 'tags': []},
    {'id': 'W_007', 'texto': 'Pie', 'nivel': 1, 'fonema': 'p', 'cat': 8, 'dif': 'baja', 'img': 'pie', 'tags': []},
    {'id': 'W_008', 'texto': 'Mamá', 'nivel': 1, 'fonema': 'm', 'cat': 9, 'dif': 'baja', 'img': 'mamá', 'tags': []},
    {'id': 'W_009', 'texto': 'Papá', 'nivel': 1, 'fonema': 'p', 'cat': 10, 'dif': 'baja', 'img': 'papá', 'tags': []},
    {'id': 'W_010', 'texto': 'Cama', 'nivel': 1, 'fonema': 'm', 'cat': 11, 'dif': 'baja', 'img': 'cama', 'tags': []},
    {'id': 'W_011', 'texto': 'Silla', 'nivel': 1, 'fonema': 'l', 'cat': 12, 'dif': 'baja', 'img': 'silla', 'tags': []},
    {'id': 'W_012', 'texto': 'Pan', 'nivel': 1, 'fonema': 'p', 'cat': 1, 'dif': 'baja', 'img': 'pan', 'tags': []},
    {'id': 'W_013', 'texto': 'Leche', 'nivel': 1, 'fonema': 'ch', 'cat': 2, 'dif': 'baja', 'img': 'leche', 'tags': []},
    {'id': 'W_014', 'texto': 'Agua', 'nivel': 1, 'fonema': 'a', 'cat': 3, 'dif': 'baja', 'img': 'agua', 'tags': []},
    {'id': 'W_015', 'texto': 'Oso', 'nivel': 1, 'fonema': 's', 'cat': 4, 'dif': 'baja', 'img': 'oso', 'tags': []},
    {'id': 'W_016', 'texto': 'Sapo', 'nivel': 1, 'fonema': 'p', 'cat': 5, 'dif': 'baja', 'img': 'sapo', 'tags': []},
    {'id': 'W_017', 'texto': 'Bebé', 'nivel': 1, 'fonema': 'b', 'cat': 6, 'dif': 'baja', 'img': 'bebé', 'tags': []},
    {'id': 'W_018', 'texto': 'Dedo', 'nivel': 1, 'fonema': 'd', 'cat': 7, 'dif': 'baja', 'img': 'dedo', 'tags': []},
    {'id': 'W_019', 'texto': 'Boca', 'nivel': 1, 'fonema': 'b', 'cat': 8, 'dif': 'baja', 'img': 'boca', 'tags': []},
    {'id': 'W_020', 'texto': 'Ojo', 'nivel': 1, 'fonema': 'o', 'cat': 9, 'dif': 'baja', 'img': 'ojo', 'tags': []},
    {'id': 'W_021', 'texto': 'Mesa', 'nivel': 1, 'fonema': 'm', 'cat': 10, 'dif': 'baja', 'img': 'mesa', 'tags': []},
    {'id': 'W_022', 'texto': 'Puerta', 'nivel': 1, 'fonema': 'p', 'cat': 11, 'dif': 'baja', 'img': 'puerta', 'tags': []},
    {'id': 'W_023', 'texto': 'Duna', 'nivel': 1, 'fonema': 'd', 'cat': 12, 'dif': 'baja', 'img': 'duna', 'tags': []},
    {'id': 'W_024', 'texto': 'Pelo', 'nivel': 1, 'fonema': 'p', 'cat': 1, 'dif': 'baja', 'img': 'pelo', 'tags': []},
    {'id': 'W_025', 'texto': 'Nube', 'nivel': 1, 'fonema': 'b', 'cat': 2, 'dif': 'baja', 'img': 'nube', 'tags': []},
    {'id': 'W_026', 'texto': 'Tío', 'nivel': 1, 'fonema': 't', 'cat': 3, 'dif': 'baja', 'img': 'tío', 'tags': []},
    {'id': 'W_027', 'texto': 'Tía', 'nivel': 1, 'fonema': 't', 'cat': 4, 'dif': 'baja', 'img': 'tía', 'tags': []},
    {'id': 'W_028', 'texto': 'Abuelo', 'nivel': 1, 'fonema': 'b', 'cat': 5, 'dif': 'baja', 'img': 'abuelo', 'tags': []},
    {'id': 'W_029', 'texto': 'Abuela', 'nivel': 1, 'fonema': 'b', 'cat': 6, 'dif': 'baja', 'img': 'abuela', 'tags': []},
    {'id': 'W_030', 'texto': 'Diente', 'nivel': 1, 'fonema': 't', 'cat': 7, 'dif': 'baja', 'img': 'diente', 'tags': []},
    {'id': 'W_031', 'texto': 'Nariz', 'nivel': 1, 'fonema': 'n', 'cat': 8, 'dif': 'baja', 'img': 'nariz', 'tags': []},
    {'id': 'W_032', 'texto': 'Pelo', 'nivel': 1, 'fonema': 'p', 'cat': 9, 'dif': 'baja', 'img': 'pelo', 'tags': []},
    {'id': 'W_033', 'texto': 'Pelota', 'nivel': 1, 'fonema': 't', 'cat': 10, 'dif': 'baja', 'img': 'pelota', 'tags': []},
    {'id': 'W_034', 'texto': 'Cubo', 'nivel': 1, 'fonema': 'b', 'cat': 11, 'dif': 'baja', 'img': 'cubo', 'tags': []},
    {'id': 'W_035', 'texto': 'Tren', 'nivel': 1, 'fonema': 'tr', 'cat': 12, 'dif': 'baja', 'img': 'tren', 'tags': []},
    {'id': 'W_036', 'texto': 'Sol', 'nivel': 1, 'fonema': 'l', 'cat': 1, 'dif': 'baja', 'img': 'sol', 'tags': []},
    {'id': 'W_037', 'texto': 'Luna', 'nivel': 1, 'fonema': 'l', 'cat': 2, 'dif': 'baja', 'img': 'luna', 'tags': []},
    {'id': 'W_038', 'texto': 'Flor', 'nivel': 1, 'fonema': 'fl', 'cat': 3, 'dif': 'baja', 'img': 'flor', 'tags': []},
    {'id': 'W_039', 'texto': 'Uva', 'nivel': 1, 'fonema': 'u', 'cat': 4, 'dif': 'baja', 'img': 'uva', 'tags': []},
    {'id': 'W_040', 'texto': 'Pera', 'nivel': 1, 'fonema': 'p', 'cat': 5, 'dif': 'baja', 'img': 'pera', 'tags': []},
    {'id': 'W_041', 'texto': 'Maíz', 'nivel': 1, 'fonema': 'm', 'cat': 6, 'dif': 'baja', 'img': 'maíz', 'tags': []},
    {'id': 'W_042', 'texto': 'Sopa', 'nivel': 1, 'fonema': 'p', 'cat': 7, 'dif': 'baja', 'img': 'sopa', 'tags': []},
    {'id': 'W_043', 'texto': 'Huevo', 'nivel': 1, 'fonema': 'h', 'cat': 8, 'dif': 'baja', 'img': 'huevo', 'tags': []},
    {'id': 'W_044', 'texto': 'Casa', 'nivel': 1, 'fonema': 's', 'cat': 9, 'dif': 'baja', 'img': 'casa', 'tags': []},
    {'id': 'W_045', 'texto': 'Vaso', 'nivel': 1, 'fonema': 's', 'cat': 10, 'dif': 'baja', 'img': 'vaso', 'tags': []},
    {'id': 'W_046', 'texto': 'Bota', 'nivel': 1, 'fonema': 'b', 'cat': 11, 'dif': 'baja', 'img': 'bota', 'tags': []},
    {'id': 'W_047', 'texto': 'Caja', 'nivel': 1, 'fonema': 'c', 'cat': 12, 'dif': 'baja', 'img': 'caja', 'tags': []},
    {'id': 'W_048', 'texto': 'Dama', 'nivel': 1, 'fonema': 'm', 'cat': 1, 'dif': 'baja', 'img': 'dama', 'tags': []},
    {'id': 'W_049', 'texto': 'Pino', 'nivel': 1, 'fonema': 'p', 'cat': 2, 'dif': 'baja', 'img': 'pino', 'tags': []},
    {'id': 'W_050', 'texto': 'Tapa', 'nivel': 1, 'fonema': 'p', 'cat': 3, 'dif': 'baja', 'img': 'tapa', 'tags': []},
    {'id': 'W_051', 'texto': 'Mapa', 'nivel': 1, 'fonema': 'p', 'cat': 4, 'dif': 'baja', 'img': 'mapa', 'tags': []},
    {'id': 'W_052', 'texto': 'Lupa', 'nivel': 1, 'fonema': 'p', 'cat': 5, 'dif': 'baja', 'img': 'lupa', 'tags': []},
    {'id': 'W_053', 'texto': 'Puma', 'nivel': 1, 'fonema': 'm', 'cat': 6, 'dif': 'baja', 'img': 'puma', 'tags': []},
    {'id': 'W_054', 'texto': 'Moto', 'nivel': 1, 'fonema': 'm', 'cat': 7, 'dif': 'baja', 'img': 'moto', 'tags': []},
    {'id': 'W_055', 'texto': 'Nene', 'nivel': 1, 'fonema': 'n', 'cat': 8, 'dif': 'baja', 'img': 'nene', 'tags': []},
    {'id': 'W_056', 'texto': 'Conejo', 'nivel': 2, 'fonema': 'n', 'cat': 9, 'dif': 'baja', 'img': 'conejo', 'tags': []},
    {'id': 'W_057', 'texto': 'Tortuga', 'nivel': 2, 'fonema': 't', 'cat': 10, 'dif': 'baja', 'img': 'tortuga', 'tags': []},
    {'id': 'W_058', 'texto': 'Jirafa', 'nivel': 2, 'fonema': 'f', 'cat': 11, 'dif': 'baja', 'img': 'jirafa', 'tags': []},
    {'id': 'W_059', 'texto': 'Elefante', 'nivel': 2, 'fonema': 't', 'cat': 12, 'dif': 'baja', 'img': 'elefante', 'tags': []},
    {'id': 'W_060', 'texto': 'Mariposa', 'nivel': 2, 'fonema': 'm', 'cat': 1, 'dif': 'baja', 'img': 'mariposa', 'tags': []},
    {'id': 'W_061', 'texto': 'Naranja', 'nivel': 2, 'fonema': 'n', 'cat': 2, 'dif': 'baja', 'img': 'naranja', 'tags': []},
    {'id': 'W_062', 'texto': 'Sandía', 'nivel': 2, 'fonema': 'd', 'cat': 3, 'dif': 'baja', 'img': 'sandía', 'tags': []},
    {'id': 'W_063', 'texto': 'Queso', 'nivel': 2, 'fonema': 's', 'cat': 4, 'dif': 'baja', 'img': 'queso', 'tags': []},
    {'id': 'W_064', 'texto': 'Pollo', 'nivel': 2, 'fonema': 'p', 'cat': 5, 'dif': 'baja', 'img': 'pollo', 'tags': []},
    {'id': 'W_065', 'texto': 'Arroz', 'nivel': 2, 'fonema': 'rr', 'cat': 6, 'dif': 'baja', 'img': 'arroz', 'tags': []},
    {'id': 'W_066', 'texto': 'Camisa', 'nivel': 2, 'fonema': 'm', 'cat': 7, 'dif': 'baja', 'img': 'camisa', 'tags': []},
    {'id': 'W_067', 'texto': 'Pantalón', 'nivel': 2, 'fonema': 'p', 'cat': 8, 'dif': 'baja', 'img': 'pantalón', 'tags': []},
    {'id': 'W_068', 'texto': 'Azul', 'nivel': 2, 'fonema': 'l', 'cat': 9, 'dif': 'baja', 'img': 'azul', 'tags': []},
    {'id': 'W_069', 'texto': 'Rojo', 'nivel': 2, 'fonema': 'r', 'cat': 10, 'dif': 'baja', 'img': 'rojo', 'tags': []},
    {'id': 'W_070', 'texto': 'Verde', 'nivel': 2, 'fonema': 'd', 'cat': 11, 'dif': 'baja', 'img': 'verde', 'tags': []},
    {'id': 'W_071', 'texto': 'Correr', 'nivel': 2, 'fonema': 'rr', 'cat': 12, 'dif': 'baja', 'img': 'correr', 'tags': []},
    {'id': 'W_072', 'texto': 'Saltar', 'nivel': 2, 'fonema': 't', 'cat': 1, 'dif': 'baja', 'img': 'saltar', 'tags': []},
    {'id': 'W_073', 'texto': 'Comer', 'nivel': 2, 'fonema': 'm', 'cat': 2, 'dif': 'baja', 'img': 'comer', 'tags': []},
    {'id': 'W_074', 'texto': 'Dormir', 'nivel': 2, 'fonema': 'm', 'cat': 3, 'dif': 'baja', 'img': 'dormir', 'tags': []},
    {'id': 'W_075', 'texto': 'Escuela', 'nivel': 2, 'fonema': 'l', 'cat': 4, 'dif': 'baja', 'img': 'escuela', 'tags': []},
    {'id': 'W_076', 'texto': 'Parque', 'nivel': 2, 'fonema': 'p', 'cat': 5, 'dif': 'baja', 'img': 'parque', 'tags': []},
    {'id': 'W_077', 'texto': 'Tienda', 'nivel': 2, 'fonema': 't', 'cat': 6, 'dif': 'baja', 'img': 'tienda', 'tags': []},
    {'id': 'W_078', 'texto': 'Bicicleta', 'nivel': 2, 'fonema': 'cl', 'cat': 7, 'dif': 'baja', 'img': 'bicicleta', 'tags': []},
    {'id': 'W_079', 'texto': 'Avión', 'nivel': 2, 'fonema': 'n', 'cat': 8, 'dif': 'baja', 'img': 'avión', 'tags': []},
    {'id': 'W_080', 'texto': 'Barco', 'nivel': 2, 'fonema': 'b', 'cat': 9, 'dif': 'baja', 'img': 'barco', 'tags': []},
    {'id': 'W_081', 'texto': 'Zapato', 'nivel': 2, 'fonema': 'p', 'cat': 10, 'dif': 'baja', 'img': 'zapato', 'tags': []},
    {'id': 'W_082', 'texto': 'Calcetín', 'nivel': 2, 'fonema': 't', 'cat': 11, 'dif': 'baja', 'img': 'calcetín', 'tags': []},
    {'id': 'W_083', 'texto': 'Sombrero', 'nivel': 2, 'fonema': 's', 'cat': 12, 'dif': 'baja', 'img': 'sombrero', 'tags': []},
    {'id': 'W_084', 'texto': 'Guante', 'nivel': 2, 'fonema': 't', 'cat': 1, 'dif': 'baja', 'img': 'guante', 'tags': []},
    {'id': 'W_085', 'texto': 'Falda', 'nivel': 2, 'fonema': 'l', 'cat': 2, 'dif': 'baja', 'img': 'falda', 'tags': []},
    {'id': 'W_086', 'texto': 'Abrigo', 'nivel': 2, 'fonema': 'br', 'cat': 3, 'dif': 'baja', 'img': 'abrigo', 'tags': []},
    {'id': 'W_087', 'texto': 'Bufanda', 'nivel': 2, 'fonema': 'f', 'cat': 4, 'dif': 'baja', 'img': 'bufanda', 'tags': []},
    {'id': 'W_088', 'texto': 'Pijama', 'nivel': 2, 'fonema': 'm', 'cat': 5, 'dif': 'baja', 'img': 'pijama', 'tags': []},
    {'id': 'W_089', 'texto': 'Yogur', 'nivel': 2, 'fonema': 'r', 'cat': 6, 'dif': 'baja', 'img': 'yogur', 'tags': []},
    {'id': 'W_090', 'texto': 'Helado', 'nivel': 2, 'fonema': 'l', 'cat': 7, 'dif': 'baja', 'img': 'helado', 'tags': []},
    {'id': 'W_091', 'texto': 'Galleta', 'nivel': 2, 'fonema': 't', 'cat': 8, 'dif': 'baja', 'img': 'galleta', 'tags': []},
    {'id': 'W_092', 'texto': 'Fresa', 'nivel': 2, 'fonema': 'f', 'cat': 9, 'dif': 'baja', 'img': 'fresa', 'tags': []},
    {'id': 'W_093', 'texto': 'Círculo', 'nivel': 2, 'fonema': 'l', 'cat': 10, 'dif': 'baja', 'img': 'círculo', 'tags': []},
    {'id': 'W_094', 'texto': 'Cuadrado', 'nivel': 2, 'fonema': 'd', 'cat': 11, 'dif': 'baja', 'img': 'cuadrado', 'tags': []},
    {'id': 'W_095', 'texto': 'Triángulo', 'nivel': 2, 'fonema': 'l', 'cat': 12, 'dif': 'baja', 'img': 'triángulo', 'tags': []},
    {'id': 'W_096', 'texto': 'Grande', 'nivel': 2, 'fonema': 'n', 'cat': 1, 'dif': 'baja', 'img': 'grande', 'tags': []},
    {'id': 'W_097', 'texto': 'Pequeño', 'nivel': 2, 'fonema': 'p', 'cat': 2, 'dif': 'baja', 'img': 'pequeño', 'tags': []},
    {'id': 'W_098', 'texto': 'Bailar', 'nivel': 2, 'fonema': 'b', 'cat': 3, 'dif': 'baja', 'img': 'bailar', 'tags': []},
    {'id': 'W_099', 'texto': 'Cantar', 'nivel': 2, 'fonema': 't', 'cat': 4, 'dif': 'baja', 'img': 'cantar', 'tags': []},
    {'id': 'W_100', 'texto': 'Nadar', 'nivel': 2, 'fonema': 'd', 'cat': 5, 'dif': 'baja', 'img': 'nadar', 'tags': []},
    {'id': 'W_101', 'texto': 'Reír', 'nivel': 2, 'fonema': 'r', 'cat': 6, 'dif': 'baja', 'img': 'reír', 'tags': []},
    {'id': 'W_102', 'texto': 'Llorar', 'nivel': 2, 'fonema': 'l', 'cat': 7, 'dif': 'baja', 'img': 'llorar', 'tags': []},
    {'id': 'W_103', 'texto': 'Jugar', 'nivel': 2, 'fonema': 'r', 'cat': 8, 'dif': 'baja', 'img': 'jugar', 'tags': []},
    {'id': 'W_104', 'texto': 'Jardín', 'nivel': 2, 'fonema': 'd', 'cat': 9, 'dif': 'baja', 'img': 'jardín', 'tags': []},
    {'id': 'W_105', 'texto': 'Cocina', 'nivel': 2, 'fonema': 'n', 'cat': 10, 'dif': 'baja', 'img': 'cocina', 'tags': []},
    {'id': 'W_106', 'texto': 'Baño', 'nivel': 2, 'fonema': 'b', 'cat': 11, 'dif': 'baja', 'img': 'baño', 'tags': []},
    {'id': 'W_107', 'texto': 'Moto', 'nivel': 2, 'fonema': 'm', 'cat': 12, 'dif': 'baja', 'img': 'moto', 'tags': []},
    {'id': 'W_108', 'texto': 'Camión', 'nivel': 2, 'fonema': 'm', 'cat': 1, 'dif': 'baja', 'img': 'camión', 'tags': []},
    {'id': 'W_109', 'texto': 'Limón', 'nivel': 2, 'fonema': 'm', 'cat': 2, 'dif': 'baja', 'img': 'limón', 'tags': []},
    {'id': 'W_110', 'texto': 'Fuego', 'nivel': 2, 'fonema': 'f', 'cat': 3, 'dif': 'baja', 'img': 'fuego', 'tags': []},
    {'id': 'W_111', 'texto': 'Silla', 'nivel': 2, 'fonema': 'l', 'cat': 4, 'dif': 'baja', 'img': 'silla', 'tags': []},
    {'id': 'W_112', 'texto': 'Llave', 'nivel': 2, 'fonema': 'l', 'cat': 5, 'dif': 'baja', 'img': 'llave', 'tags': []},
    {'id': 'W_113', 'texto': 'Nido', 'nivel': 2, 'fonema': 'd', 'cat': 6, 'dif': 'baja', 'img': 'nido', 'tags': []},
    {'id': 'W_114', 'texto': 'Foca', 'nivel': 2, 'fonema': 'f', 'cat': 7, 'dif': 'baja', 'img': 'foca', 'tags': []},
    {'id': 'W_115', 'texto': 'Gallo', 'nivel': 2, 'fonema': 'l', 'cat': 8, 'dif': 'baja', 'img': 'gallo', 'tags': []},
    {'id': 'W_116', 'texto': 'Hormiga', 'nivel': 2, 'fonema': 'm', 'cat': 9, 'dif': 'baja', 'img': 'hormiga', 'tags': []},
    {'id': 'W_117', 'texto': 'Gallina', 'nivel': 2, 'fonema': 'l', 'cat': 10, 'dif': 'baja', 'img': 'gallina', 'tags': []},
    {'id': 'W_118', 'texto': 'Caballo', 'nivel': 2, 'fonema': 'b', 'cat': 11, 'dif': 'baja', 'img': 'caballo', 'tags': []},
    {'id': 'W_119', 'texto': 'Loro', 'nivel': 2, 'fonema': 'l', 'cat': 12, 'dif': 'baja', 'img': 'loro', 'tags': []},
    {'id': 'W_120', 'texto': 'Rana', 'nivel': 2, 'fonema': 'n', 'cat': 1, 'dif': 'baja', 'img': 'rana', 'tags': []},
    {'id': 'W_121', 'texto': 'Dragón', 'nivel': 3, 'fonema': 'd', 'cat': 2, 'dif': 'media', 'img': 'dragón', 'tags': []},
    {'id': 'W_122', 'texto': 'Cocodrilo', 'nivel': 3, 'fonema': 'd', 'cat': 3, 'dif': 'media', 'img': 'cocodrilo', 'tags': []},
    {'id': 'W_123', 'texto': 'Flamenco', 'nivel': 3, 'fonema': 'fl', 'cat': 4, 'dif': 'media', 'img': 'flamenco', 'tags': []},
    {'id': 'W_124', 'texto': 'Grillo', 'nivel': 3, 'fonema': 'gr', 'cat': 5, 'dif': 'media', 'img': 'grillo', 'tags': []},
    {'id': 'W_125', 'texto': 'Delfín', 'nivel': 3, 'fonema': 'd', 'cat': 6, 'dif': 'media', 'img': 'delfín', 'tags': []},
    {'id': 'W_126', 'texto': 'Tigre', 'nivel': 3, 'fonema': 'gr', 'cat': 7, 'dif': 'media', 'img': 'tigre', 'tags': []},
    {'id': 'W_127', 'texto': 'Árbol', 'nivel': 3, 'fonema': 'b', 'cat': 8, 'dif': 'media', 'img': 'árbol', 'tags': []},
    {'id': 'W_128', 'texto': 'Piedra', 'nivel': 3, 'fonema': 'r', 'cat': 9, 'dif': 'media', 'img': 'piedra', 'tags': []},
    {'id': 'W_129', 'texto': 'Trueno', 'nivel': 3, 'fonema': 'tr', 'cat': 10, 'dif': 'media', 'img': 'trueno', 'tags': []},
    {'id': 'W_130', 'texto': 'Playa', 'nivel': 3, 'fonema': 'pl', 'cat': 11, 'dif': 'media', 'img': 'playa', 'tags': []},
    {'id': 'W_131', 'texto': 'Bosque', 'nivel': 3, 'fonema': 'b', 'cat': 12, 'dif': 'media', 'img': 'bosque', 'tags': []},
    {'id': 'W_132', 'texto': 'Volcán', 'nivel': 3, 'fonema': 'l', 'cat': 1, 'dif': 'media', 'img': 'volcán', 'tags': []},
    {'id': 'W_133', 'texto': 'Estrella', 'nivel': 3, 'fonema': 'tr', 'cat': 2, 'dif': 'media', 'img': 'estrella', 'tags': []},
    {'id': 'W_134', 'texto': 'Helicóptero', 'nivel': 3, 'fonema': 'p', 'cat': 3, 'dif': 'media', 'img': 'helicóptero', 'tags': []},
    {'id': 'W_135', 'texto': 'Grúa', 'nivel': 3, 'fonema': 'gr', 'cat': 4, 'dif': 'media', 'img': 'grúa', 'tags': []},
    {'id': 'W_136', 'texto': 'Tractór', 'nivel': 3, 'fonema': 'r', 'cat': 5, 'dif': 'media', 'img': 'tractór', 'tags': []},
    {'id': 'W_137', 'texto': 'Submarino', 'nivel': 3, 'fonema': 'm', 'cat': 6, 'dif': 'media', 'img': 'submarino', 'tags': []},
    {'id': 'W_138', 'texto': 'Trineo', 'nivel': 3, 'fonema': 'tr', 'cat': 7, 'dif': 'media', 'img': 'trineo', 'tags': []},
    {'id': 'W_139', 'texto': 'Patín', 'nivel': 3, 'fonema': 'p', 'cat': 8, 'dif': 'media', 'img': 'patín', 'tags': []},
    {'id': 'W_140', 'texto': 'Trepar', 'nivel': 3, 'fonema': 'tr', 'cat': 9, 'dif': 'media', 'img': 'trepar', 'tags': []},
    {'id': 'W_141', 'texto': 'Gritar', 'nivel': 3, 'fonema': 'gr', 'cat': 10, 'dif': 'media', 'img': 'gritar', 'tags': []},
    {'id': 'W_142', 'texto': 'Frotar', 'nivel': 3, 'fonema': 't', 'cat': 11, 'dif': 'media', 'img': 'frotar', 'tags': []},
    {'id': 'W_143', 'texto': 'Abrazar', 'nivel': 3, 'fonema': 'br', 'cat': 12, 'dif': 'media', 'img': 'abrazar', 'tags': []},
    {'id': 'W_144', 'texto': 'Dibujar', 'nivel': 3, 'fonema': 'r', 'cat': 1, 'dif': 'media', 'img': 'dibujar', 'tags': []},
    {'id': 'W_145', 'texto': 'Construir', 'nivel': 3, 'fonema': 'tr', 'cat': 2, 'dif': 'media', 'img': 'construir', 'tags': []},
    {'id': 'W_146', 'texto': 'Plantar', 'nivel': 3, 'fonema': 'pl', 'cat': 3, 'dif': 'media', 'img': 'plantar', 'tags': []},
    {'id': 'W_147', 'texto': 'Preparar', 'nivel': 3, 'fonema': 'p', 'cat': 4, 'dif': 'media', 'img': 'preparar', 'tags': []},
    {'id': 'W_148', 'texto': 'Explorar', 'nivel': 3, 'fonema': 'pl', 'cat': 5, 'dif': 'media', 'img': 'explorar', 'tags': []},
    {'id': 'W_149', 'texto': 'Trabajar', 'nivel': 3, 'fonema': 'tr', 'cat': 6, 'dif': 'media', 'img': 'trabajar', 'tags': []},
    {'id': 'W_150', 'texto': 'Escribir', 'nivel': 3, 'fonema': 'b', 'cat': 7, 'dif': 'media', 'img': 'escribir', 'tags': []},
    {'id': 'W_151', 'texto': 'Limpiar', 'nivel': 3, 'fonema': 'm', 'cat': 8, 'dif': 'media', 'img': 'limpiar', 'tags': []},
    {'id': 'W_152', 'texto': 'Feliz', 'nivel': 3, 'fonema': 'l', 'cat': 9, 'dif': 'media', 'img': 'feliz', 'tags': []},
    {'id': 'W_153', 'texto': 'Triste', 'nivel': 3, 'fonema': 'tr', 'cat': 10, 'dif': 'media', 'img': 'triste', 'tags': []},
    {'id': 'W_154', 'texto': 'Enojado', 'nivel': 3, 'fonema': 'd', 'cat': 11, 'dif': 'media', 'img': 'enojado', 'tags': []},
    {'id': 'W_155', 'texto': 'Asustado', 'nivel': 3, 'fonema': 't', 'cat': 12, 'dif': 'media', 'img': 'asustado', 'tags': []},
    {'id': 'W_156', 'texto': 'Sorprendido', 'nivel': 3, 'fonema': 'p', 'cat': 1, 'dif': 'media', 'img': 'sorprendido', 'tags': []},
    {'id': 'W_157', 'texto': 'Aburrido', 'nivel': 3, 'fonema': 'rr', 'cat': 2, 'dif': 'media', 'img': 'aburrido', 'tags': []},
    {'id': 'W_158', 'texto': 'Doctor', 'nivel': 3, 'fonema': 't', 'cat': 3, 'dif': 'media', 'img': 'doctor', 'tags': []},
    {'id': 'W_159', 'texto': 'Bombero', 'nivel': 3, 'fonema': 'm', 'cat': 4, 'dif': 'media', 'img': 'bombero', 'tags': []},
    {'id': 'W_160', 'texto': 'Maestro', 'nivel': 3, 'fonema': 'r', 'cat': 5, 'dif': 'media', 'img': 'maestro', 'tags': []},
    {'id': 'W_161', 'texto': 'Cocinero', 'nivel': 3, 'fonema': 'n', 'cat': 6, 'dif': 'media', 'img': 'cocinero', 'tags': []},
    {'id': 'W_162', 'texto': 'Policía', 'nivel': 3, 'fonema': 'p', 'cat': 7, 'dif': 'media', 'img': 'policía', 'tags': []},
    {'id': 'W_163', 'texto': 'Rápido', 'nivel': 3, 'fonema': 'p', 'cat': 8, 'dif': 'media', 'img': 'rápido', 'tags': []},
    {'id': 'W_164', 'texto': 'Lento', 'nivel': 3, 'fonema': 't', 'cat': 9, 'dif': 'media', 'img': 'lento', 'tags': []},
    {'id': 'W_165', 'texto': 'Suave', 'nivel': 3, 'fonema': 's', 'cat': 10, 'dif': 'media', 'img': 'suave', 'tags': []},
    {'id': 'W_166', 'texto': 'Rugoso', 'nivel': 3, 'fonema': 's', 'cat': 11, 'dif': 'media', 'img': 'rugoso', 'tags': []},
    {'id': 'W_167', 'texto': 'Brillante', 'nivel': 3, 'fonema': 'br', 'cat': 12, 'dif': 'media', 'img': 'brillante', 'tags': []},
    {'id': 'W_168', 'texto': 'Ventana', 'nivel': 3, 'fonema': 't', 'cat': 1, 'dif': 'media', 'img': 'ventana', 'tags': []},
    {'id': 'W_169', 'texto': 'Escalera', 'nivel': 3, 'fonema': 'l', 'cat': 2, 'dif': 'media', 'img': 'escalera', 'tags': []},
    {'id': 'W_170', 'texto': 'Techo', 'nivel': 3, 'fonema': 'ch', 'cat': 3, 'dif': 'media', 'img': 'techo', 'tags': []},
    {'id': 'W_171', 'texto': 'Garaje', 'nivel': 3, 'fonema': 'r', 'cat': 4, 'dif': 'media', 'img': 'garaje', 'tags': []},
    {'id': 'W_172', 'texto': 'Sótano', 'nivel': 3, 'fonema': 't', 'cat': 5, 'dif': 'media', 'img': 'sótano', 'tags': []},
    {'id': 'W_173', 'texto': 'Balcón', 'nivel': 3, 'fonema': 'b', 'cat': 6, 'dif': 'media', 'img': 'balcón', 'tags': []},
    {'id': 'W_174', 'texto': 'Planeta', 'nivel': 3, 'fonema': 'pl', 'cat': 7, 'dif': 'media', 'img': 'planeta', 'tags': []},
    {'id': 'W_175', 'texto': 'Cometa', 'nivel': 3, 'fonema': 'm', 'cat': 8, 'dif': 'media', 'img': 'cometa', 'tags': []},
    {'id': 'W_176', 'texto': 'Princesa', 'nivel': 3, 'fonema': 'r', 'cat': 9, 'dif': 'media', 'img': 'princesa', 'tags': []},
    {'id': 'W_177', 'texto': 'Príncipe', 'nivel': 3, 'fonema': 'p', 'cat': 10, 'dif': 'media', 'img': 'príncipe', 'tags': []},
    {'id': 'W_178', 'texto': 'Globo', 'nivel': 3, 'fonema': 'b', 'cat': 11, 'dif': 'media', 'img': 'globo', 'tags': []},
    {'id': 'W_179', 'texto': 'Plato', 'nivel': 3, 'fonema': 'pl', 'cat': 12, 'dif': 'media', 'img': 'plato', 'tags': []},
    {'id': 'W_180', 'texto': 'Blusa', 'nivel': 3, 'fonema': 'b', 'cat': 1, 'dif': 'media', 'img': 'blusa', 'tags': []},
    {'id': 'W_181', 'texto': 'Clavo', 'nivel': 3, 'fonema': 'cl', 'cat': 2, 'dif': 'media', 'img': 'clavo', 'tags': []},
    {'id': 'W_182', 'texto': 'Flauta', 'nivel': 3, 'fonema': 'fl', 'cat': 3, 'dif': 'media', 'img': 'flauta', 'tags': []},
    {'id': 'W_183', 'texto': 'Fruta', 'nivel': 3, 'fonema': 't', 'cat': 4, 'dif': 'media', 'img': 'fruta', 'tags': []},
    {'id': 'W_184', 'texto': 'Gruta', 'nivel': 3, 'fonema': 'r', 'cat': 5, 'dif': 'media', 'img': 'gruta', 'tags': []},
    {'id': 'W_185', 'texto': 'Pluma', 'nivel': 3, 'fonema': 'pl', 'cat': 6, 'dif': 'media', 'img': 'pluma', 'tags': []},
    {'id': 'W_186', 'texto': 'Brazo', 'nivel': 3, 'fonema': 'br', 'cat': 7, 'dif': 'media', 'img': 'brazo', 'tags': []},
    {'id': 'W_187', 'texto': 'Crema', 'nivel': 3, 'fonema': 'm', 'cat': 8, 'dif': 'media', 'img': 'crema', 'tags': []},
    {'id': 'W_188', 'texto': 'Freno', 'nivel': 3, 'fonema': 'n', 'cat': 9, 'dif': 'media', 'img': 'freno', 'tags': []},
    {'id': 'W_189', 'texto': 'Grano', 'nivel': 3, 'fonema': 'gr', 'cat': 10, 'dif': 'media', 'img': 'grano', 'tags': []},
    {'id': 'W_190', 'texto': 'Presa', 'nivel': 3, 'fonema': 'p', 'cat': 11, 'dif': 'media', 'img': 'presa', 'tags': []},
    {'id': 'W_191', 'texto': 'Trigo', 'nivel': 3, 'fonema': 'tr', 'cat': 12, 'dif': 'media', 'img': 'trigo', 'tags': []},
    {'id': 'W_192', 'texto': 'Clima', 'nivel': 3, 'fonema': 'cl', 'cat': 1, 'dif': 'media', 'img': 'clima', 'tags': []},
    {'id': 'W_193', 'texto': 'Flecha', 'nivel': 3, 'fonema': 'fl', 'cat': 2, 'dif': 'media', 'img': 'flecha', 'tags': []},
    {'id': 'W_194', 'texto': 'Plomo', 'nivel': 3, 'fonema': 'pl', 'cat': 3, 'dif': 'media', 'img': 'plomo', 'tags': []},
    {'id': 'W_195', 'texto': 'Canguro', 'nivel': 3, 'fonema': 'n', 'cat': 4, 'dif': 'media', 'img': 'canguro', 'tags': []},
    {'id': 'W_196', 'texto': 'Frustración', 'nivel': 4, 'fonema': 'tr', 'cat': 5, 'dif': 'media', 'img': 'frustración', 'tags': []},
    {'id': 'W_197', 'texto': 'Entusiasmo', 'nivel': 4, 'fonema': 'm', 'cat': 6, 'dif': 'media', 'img': 'entusiasmo', 'tags': []},
    {'id': 'W_198', 'texto': 'Nostalgia', 'nivel': 4, 'fonema': 't', 'cat': 7, 'dif': 'media', 'img': 'nostalgia', 'tags': []},
    {'id': 'W_199', 'texto': 'Decepción', 'nivel': 4, 'fonema': 'p', 'cat': 8, 'dif': 'media', 'img': 'decepción', 'tags': []},
    {'id': 'W_200', 'texto': 'Gratitud', 'nivel': 4, 'fonema': 'r', 'cat': 9, 'dif': 'media', 'img': 'gratitud', 'tags': []},
    {'id': 'W_201', 'texto': 'Valentía', 'nivel': 4, 'fonema': 't', 'cat': 10, 'dif': 'media', 'img': 'valentía', 'tags': []},
    {'id': 'W_202', 'texto': 'Vergüenza', 'nivel': 4, 'fonema': 'n', 'cat': 11, 'dif': 'media', 'img': 'vergüenza', 'tags': []},
    {'id': 'W_203', 'texto': 'Envidia', 'nivel': 4, 'fonema': 'd', 'cat': 12, 'dif': 'media', 'img': 'envidia', 'tags': []},
    {'id': 'W_204', 'texto': 'Confianza', 'nivel': 4, 'fonema': 'n', 'cat': 1, 'dif': 'media', 'img': 'confianza', 'tags': []},
    {'id': 'W_205', 'texto': 'Soledad', 'nivel': 4, 'fonema': 'd', 'cat': 2, 'dif': 'media', 'img': 'soledad', 'tags': []},
    {'id': 'W_206', 'texto': 'Gravedad', 'nivel': 4, 'fonema': 'gr', 'cat': 3, 'dif': 'media', 'img': 'gravedad', 'tags': []},
    {'id': 'W_207', 'texto': 'Evaporación', 'nivel': 4, 'fonema': 'p', 'cat': 4, 'dif': 'media', 'img': 'evaporación', 'tags': []},
    {'id': 'W_208', 'texto': 'Fotosíntesis', 'nivel': 4, 'fonema': 't', 'cat': 5, 'dif': 'media', 'img': 'fotosíntesis', 'tags': []},
    {'id': 'W_209', 'texto': 'Eclipse', 'nivel': 4, 'fonema': 'cl', 'cat': 6, 'dif': 'media', 'img': 'eclipse', 'tags': []},
    {'id': 'W_210', 'texto': 'Terremoto', 'nivel': 4, 'fonema': 'rr', 'cat': 7, 'dif': 'media', 'img': 'terremoto', 'tags': []},
    {'id': 'W_211', 'texto': 'Atmósfera', 'nivel': 4, 'fonema': 'm', 'cat': 8, 'dif': 'media', 'img': 'atmósfera', 'tags': []},
    {'id': 'W_212', 'texto': 'Cristal', 'nivel': 4, 'fonema': 't', 'cat': 9, 'dif': 'media', 'img': 'cristal', 'tags': []},
    {'id': 'W_213', 'texto': 'Imán', 'nivel': 4, 'fonema': 'm', 'cat': 10, 'dif': 'media', 'img': 'imán', 'tags': []},
    {'id': 'W_214', 'texto': 'Energía', 'nivel': 4, 'fonema': 'n', 'cat': 11, 'dif': 'media', 'img': 'energía', 'tags': []},
    {'id': 'W_215', 'texto': 'Oxígeno', 'nivel': 4, 'fonema': 'n', 'cat': 12, 'dif': 'media', 'img': 'oxígeno', 'tags': []},
    {'id': 'W_216', 'texto': 'Ecosistema', 'nivel': 4, 'fonema': 'm', 'cat': 1, 'dif': 'media', 'img': 'ecosistema', 'tags': []},
    {'id': 'W_217', 'texto': 'Arqueólogo', 'nivel': 4, 'fonema': 'l', 'cat': 2, 'dif': 'media', 'img': 'arqueólogo', 'tags': []},
    {'id': 'W_218', 'texto': 'Astronauta', 'nivel': 4, 'fonema': 'tr', 'cat': 3, 'dif': 'media', 'img': 'astronauta', 'tags': []},
    {'id': 'W_219', 'texto': 'Veterinario', 'nivel': 4, 'fonema': 't', 'cat': 4, 'dif': 'media', 'img': 'veterinario', 'tags': []},
    {'id': 'W_220', 'texto': 'Científico', 'nivel': 4, 'fonema': 't', 'cat': 5, 'dif': 'media', 'img': 'científico', 'tags': []},
    {'id': 'W_221', 'texto': 'Arquitecto', 'nivel': 4, 'fonema': 't', 'cat': 6, 'dif': 'media', 'img': 'arquitecto', 'tags': []},
    {'id': 'W_222', 'texto': 'Periodista', 'nivel': 4, 'fonema': 'p', 'cat': 7, 'dif': 'media', 'img': 'periodista', 'tags': []},
    {'id': 'W_223', 'texto': 'Programador', 'nivel': 4, 'fonema': 'gr', 'cat': 8, 'dif': 'media', 'img': 'programador', 'tags': []},
    {'id': 'W_224', 'texto': 'Atleta', 'nivel': 4, 'fonema': 't', 'cat': 9, 'dif': 'media', 'img': 'atleta', 'tags': []},
    {'id': 'W_225', 'texto': 'Músico', 'nivel': 4, 'fonema': 'm', 'cat': 10, 'dif': 'media', 'img': 'músico', 'tags': []},
    {'id': 'W_226', 'texto': 'Filósofo', 'nivel': 4, 'fonema': 'l', 'cat': 11, 'dif': 'media', 'img': 'filósofo', 'tags': []},
    {'id': 'W_227', 'texto': 'Imaginar', 'nivel': 4, 'fonema': 'm', 'cat': 12, 'dif': 'media', 'img': 'imaginar', 'tags': []},
    {'id': 'W_228', 'texto': 'Resolver', 'nivel': 4, 'fonema': 'l', 'cat': 1, 'dif': 'media', 'img': 'resolver', 'tags': []},
    {'id': 'W_229', 'texto': 'Comparar', 'nivel': 4, 'fonema': 'm', 'cat': 2, 'dif': 'media', 'img': 'comparar', 'tags': []},
    {'id': 'W_230', 'texto': 'Describir', 'nivel': 4, 'fonema': 'b', 'cat': 3, 'dif': 'media', 'img': 'describir', 'tags': []},
    {'id': 'W_231', 'texto': 'Analizar', 'nivel': 4, 'fonema': 'l', 'cat': 4, 'dif': 'media', 'img': 'analizar', 'tags': []},
    {'id': 'W_232', 'texto': 'Recordar', 'nivel': 4, 'fonema': 'r', 'cat': 5, 'dif': 'media', 'img': 'recordar', 'tags': []},
    {'id': 'W_233', 'texto': 'Predecir', 'nivel': 4, 'fonema': 'p', 'cat': 6, 'dif': 'media', 'img': 'predecir', 'tags': []},
    {'id': 'W_234', 'texto': 'Reflexionar', 'nivel': 4, 'fonema': 'fl', 'cat': 7, 'dif': 'media', 'img': 'reflexionar', 'tags': []},
    {'id': 'W_235', 'texto': 'Organizar', 'nivel': 4, 'fonema': 'n', 'cat': 8, 'dif': 'media', 'img': 'organizar', 'tags': []},
    {'id': 'W_236', 'texto': 'Opinar', 'nivel': 4, 'fonema': 'p', 'cat': 9, 'dif': 'media', 'img': 'opinar', 'tags': []},
    {'id': 'W_237', 'texto': 'Continente', 'nivel': 4, 'fonema': 't', 'cat': 10, 'dif': 'media', 'img': 'continente', 'tags': []},
    {'id': 'W_238', 'texto': 'Desierto', 'nivel': 4, 'fonema': 't', 'cat': 11, 'dif': 'media', 'img': 'desierto', 'tags': []},
    {'id': 'W_239', 'texto': 'Selva', 'nivel': 4, 'fonema': 'l', 'cat': 12, 'dif': 'media', 'img': 'selva', 'tags': []},
    {'id': 'W_240', 'texto': 'Polo', 'nivel': 4, 'fonema': 'p', 'cat': 1, 'dif': 'media', 'img': 'polo', 'tags': []},
    {'id': 'W_241', 'texto': 'Océano', 'nivel': 4, 'fonema': 'n', 'cat': 2, 'dif': 'media', 'img': 'océano', 'tags': []},
    {'id': 'W_242', 'texto': 'Ciudad', 'nivel': 4, 'fonema': 'd', 'cat': 3, 'dif': 'media', 'img': 'ciudad', 'tags': []},
    {'id': 'W_243', 'texto': 'Aldea', 'nivel': 4, 'fonema': 'd', 'cat': 4, 'dif': 'media', 'img': 'aldea', 'tags': []},
    {'id': 'W_244', 'texto': 'Frontera', 'nivel': 4, 'fonema': 't', 'cat': 5, 'dif': 'media', 'img': 'frontera', 'tags': []},
    {'id': 'W_245', 'texto': 'Capital', 'nivel': 4, 'fonema': 'p', 'cat': 6, 'dif': 'media', 'img': 'capital', 'tags': []},
    {'id': 'W_246', 'texto': 'Archipiélago', 'nivel': 4, 'fonema': 'ch', 'cat': 7, 'dif': 'media', 'img': 'archipiélago', 'tags': []},
    {'id': 'W_247', 'texto': 'Ayer', 'nivel': 4, 'fonema': 'r', 'cat': 8, 'dif': 'media', 'img': 'ayer', 'tags': []},
    {'id': 'W_248', 'texto': 'Mañana', 'nivel': 4, 'fonema': 'm', 'cat': 9, 'dif': 'media', 'img': 'mañana', 'tags': []},
    {'id': 'W_249', 'texto': 'Siempre', 'nivel': 4, 'fonema': 'm', 'cat': 10, 'dif': 'media', 'img': 'siempre', 'tags': []},
    {'id': 'W_250', 'texto': 'Nunca', 'nivel': 4, 'fonema': 'n', 'cat': 11, 'dif': 'media', 'img': 'nunca', 'tags': []},
    {'id': 'W_251', 'texto': 'Mientras', 'nivel': 4, 'fonema': 'tr', 'cat': 12, 'dif': 'media', 'img': 'mientras', 'tags': []},
    {'id': 'W_252', 'texto': 'Durante', 'nivel': 4, 'fonema': 't', 'cat': 1, 'dif': 'media', 'img': 'durante', 'tags': []},
    {'id': 'W_253', 'texto': 'Después', 'nivel': 4, 'fonema': 'p', 'cat': 2, 'dif': 'media', 'img': 'después', 'tags': []},
    {'id': 'W_254', 'texto': 'Antes', 'nivel': 4, 'fonema': 't', 'cat': 3, 'dif': 'media', 'img': 'antes', 'tags': []},
    {'id': 'W_255', 'texto': 'Relatividad', 'nivel': 4, 'fonema': 't', 'cat': 4, 'dif': 'media', 'img': 'relatividad', 'tags': []},
    {'id': 'W_256', 'texto': 'Genética', 'nivel': 4, 'fonema': 't', 'cat': 5, 'dif': 'media', 'img': 'genética', 'tags': []},
    {'id': 'W_257', 'texto': 'Justicia', 'nivel': 5, 'fonema': 't', 'cat': 6, 'dif': 'alta', 'img': 'justicia', 'tags': []},
    {'id': 'W_258', 'texto': 'Libertad', 'nivel': 5, 'fonema': 'b', 'cat': 7, 'dif': 'alta', 'img': 'libertad', 'tags': []},
    {'id': 'W_259', 'texto': 'Democracia', 'nivel': 5, 'fonema': 'm', 'cat': 8, 'dif': 'alta', 'img': 'democracia', 'tags': []},
    {'id': 'W_260', 'texto': 'Responsabilidad', 'nivel': 5, 'fonema': 'p', 'cat': 9, 'dif': 'alta', 'img': 'responsabilidad', 'tags': []},
    {'id': 'W_261', 'texto': 'Creatividad', 'nivel': 5, 'fonema': 't', 'cat': 10, 'dif': 'alta', 'img': 'creatividad', 'tags': []},
    {'id': 'W_262', 'texto': 'Solidaridad', 'nivel': 5, 'fonema': 'd', 'cat': 11, 'dif': 'alta', 'img': 'solidaridad', 'tags': []},
    {'id': 'W_263', 'texto': 'Ética', 'nivel': 5, 'fonema': 't', 'cat': 12, 'dif': 'alta', 'img': 'ética', 'tags': []},
    {'id': 'W_264', 'texto': 'Tolerancia', 'nivel': 5, 'fonema': 'r', 'cat': 1, 'dif': 'alta', 'img': 'tolerancia', 'tags': []},
    {'id': 'W_265', 'texto': 'Identidad', 'nivel': 5, 'fonema': 't', 'cat': 2, 'dif': 'alta', 'img': 'identidad', 'tags': []},
    {'id': 'W_266', 'texto': 'Cultura', 'nivel': 5, 'fonema': 't', 'cat': 3, 'dif': 'alta', 'img': 'cultura', 'tags': []},
    {'id': 'W_267', 'texto': 'Evolución', 'nivel': 5, 'fonema': 'l', 'cat': 4, 'dif': 'alta', 'img': 'evolución', 'tags': []},
    {'id': 'W_268', 'texto': 'Perspectiva', 'nivel': 5, 'fonema': 'p', 'cat': 5, 'dif': 'alta', 'img': 'perspectiva', 'tags': []},
    {'id': 'W_269', 'texto': 'Hipótesis', 'nivel': 5, 'fonema': 'p', 'cat': 6, 'dif': 'alta', 'img': 'hipótesis', 'tags': []},
    {'id': 'W_270', 'texto': 'Evidencia', 'nivel': 5, 'fonema': 'd', 'cat': 7, 'dif': 'alta', 'img': 'evidencia', 'tags': []},
    {'id': 'W_271', 'texto': 'Argumento', 'nivel': 5, 'fonema': 'm', 'cat': 8, 'dif': 'alta', 'img': 'argumento', 'tags': []},
    {'id': 'W_272', 'texto': 'Conclusión', 'nivel': 5, 'fonema': 'cl', 'cat': 9, 'dif': 'alta', 'img': 'conclusión', 'tags': []},
    {'id': 'W_273', 'texto': 'Síntesis', 'nivel': 5, 'fonema': 't', 'cat': 10, 'dif': 'alta', 'img': 'síntesis', 'tags': []},
    {'id': 'W_274', 'texto': 'Metáfora', 'nivel': 5, 'fonema': 'm', 'cat': 11, 'dif': 'alta', 'img': 'metáfora', 'tags': []},
    {'id': 'W_275', 'texto': 'Protagonista', 'nivel': 5, 'fonema': 'p', 'cat': 12, 'dif': 'alta', 'img': 'protagonista', 'tags': []},
    {'id': 'W_276', 'texto': 'Antagonista', 'nivel': 5, 'fonema': 't', 'cat': 1, 'dif': 'alta', 'img': 'antagonista', 'tags': []},
    {'id': 'W_277', 'texto': 'Narrador', 'nivel': 5, 'fonema': 'rr', 'cat': 2, 'dif': 'alta', 'img': 'narrador', 'tags': []},
    {'id': 'W_278', 'texto': 'Rima', 'nivel': 5, 'fonema': 'm', 'cat': 3, 'dif': 'alta', 'img': 'rima', 'tags': []},
    {'id': 'W_279', 'texto': 'Estrofa', 'nivel': 5, 'fonema': 'tr', 'cat': 4, 'dif': 'alta', 'img': 'estrofa', 'tags': []},
    {'id': 'W_280', 'texto': 'Párrafo', 'nivel': 5, 'fonema': 'r', 'cat': 5, 'dif': 'alta', 'img': 'párrafo', 'tags': []},
    {'id': 'W_281', 'texto': 'Deducir', 'nivel': 5, 'fonema': 'd', 'cat': 6, 'dif': 'alta', 'img': 'deducir', 'tags': []},
    {'id': 'W_282', 'texto': 'Inferir', 'nivel': 5, 'fonema': 'n', 'cat': 7, 'dif': 'alta', 'img': 'inferir', 'tags': []},
    {'id': 'W_283', 'texto': 'Sintetizar', 'nivel': 5, 'fonema': 't', 'cat': 8, 'dif': 'alta', 'img': 'sintetizar', 'tags': []},
    {'id': 'W_284', 'texto': 'Contextualizar', 'nivel': 5, 'fonema': 't', 'cat': 9, 'dif': 'alta', 'img': 'contextualizar', 'tags': []},
    {'id': 'W_285', 'texto': 'Argumentar', 'nivel': 5, 'fonema': 'm', 'cat': 10, 'dif': 'alta', 'img': 'argumentar', 'tags': []},
    {'id': 'W_286', 'texto': 'Evaluar', 'nivel': 5, 'fonema': 'l', 'cat': 11, 'dif': 'alta', 'img': 'evaluar', 'tags': []},
    {'id': 'W_287', 'texto': 'Debatir', 'nivel': 5, 'fonema': 'b', 'cat': 12, 'dif': 'alta', 'img': 'debatir', 'tags': []},
    {'id': 'W_288', 'texto': 'Contrastar', 'nivel': 5, 'fonema': 'r', 'cat': 1, 'dif': 'alta', 'img': 'contrastar', 'tags': []},
    {'id': 'W_289', 'texto': 'Justificar', 'nivel': 5, 'fonema': 't', 'cat': 2, 'dif': 'alta', 'img': 'justificar', 'tags': []},
    {'id': 'W_290', 'texto': 'Hipotetizar', 'nivel': 5, 'fonema': 'p', 'cat': 3, 'dif': 'alta', 'img': 'hipotetizar', 'tags': []},
    {'id': 'W_291', 'texto': 'Clasificar', 'nivel': 5, 'fonema': 'cl', 'cat': 4, 'dif': 'alta', 'img': 'clasificar', 'tags': []},
    {'id': 'W_292', 'texto': 'Formular', 'nivel': 5, 'fonema': 'm', 'cat': 5, 'dif': 'alta', 'img': 'formular', 'tags': []},
    {'id': 'W_293', 'texto': 'Lloviendo a cántaros', 'nivel': 5, 'fonema': 't', 'cat': 6, 'dif': 'alta', 'img': 'lloviendo_a_cántaros', 'tags': []},
    {'id': 'W_294', 'texto': 'Ojo de la cara', 'nivel': 5, 'fonema': 'd', 'cat': 7, 'dif': 'alta', 'img': 'ojo_de_la_cara', 'tags': []},
    {'id': 'W_295', 'texto': 'Pez gordo', 'nivel': 5, 'fonema': 'p', 'cat': 8, 'dif': 'alta', 'img': 'pez_gordo', 'tags': []},
    {'id': 'W_296', 'texto': 'Mano izquierda', 'nivel': 5, 'fonema': 'r', 'cat': 9, 'dif': 'alta', 'img': 'mano_izquierda', 'tags': []},
    {'id': 'W_297', 'texto': 'Pisar el acelerador', 'nivel': 5, 'fonema': 'p', 'cat': 10, 'dif': 'alta', 'img': 'pisar_el_acelerador', 'tags': []},
    {'id': 'W_298', 'texto': 'Romper el hielo', 'nivel': 5, 'fonema': 'm', 'cat': 11, 'dif': 'alta', 'img': 'romper_el_hielo', 'tags': []},
    {'id': 'W_299', 'texto': 'Tirar la toalla', 'nivel': 5, 'fonema': 't', 'cat': 12, 'dif': 'alta', 'img': 'tirar_la_toalla', 'tags': []},
    {'id': 'W_300', 'texto': 'Sin embargo', 'nivel': 5, 'fonema': 'm', 'cat': 1, 'dif': 'alta', 'img': 'sin_embargo', 'tags': []},
    {'id': 'W_301', 'texto': 'Por lo tanto', 'nivel': 5, 'fonema': 'p', 'cat': 2, 'dif': 'alta', 'img': 'por_lo_tanto', 'tags': []},
    {'id': 'W_302', 'texto': 'A pesar de', 'nivel': 5, 'fonema': 'p', 'cat': 3, 'dif': 'alta', 'img': 'a_pesar_de', 'tags': []},
    {'id': 'W_303', 'texto': 'Consecuencia', 'nivel': 5, 'fonema': 'n', 'cat': 4, 'dif': 'alta', 'img': 'consecuencia', 'tags': []},
    {'id': 'W_304', 'texto': 'No obstante', 'nivel': 5, 'fonema': 'b', 'cat': 5, 'dif': 'alta', 'img': 'no_obstante', 'tags': []},
    {'id': 'W_305', 'texto': 'Es decir', 'nivel': 5, 'fonema': 'd', 'cat': 6, 'dif': 'alta', 'img': 'es_decir', 'tags': []},
    {'id': 'W_306', 'texto': 'En resumen', 'nivel': 5, 'fonema': 'm', 'cat': 7, 'dif': 'alta', 'img': 'en_resumen', 'tags': []},
    {'id': 'W_307', 'texto': 'Asimismo', 'nivel': 5, 'fonema': 'm', 'cat': 8, 'dif': 'alta', 'img': 'asimismo', 'tags': []},
    {'id': 'W_308', 'texto': 'Aunque', 'nivel': 5, 'fonema': 'n', 'cat': 9, 'dif': 'alta', 'img': 'aunque', 'tags': []},
    {'id': 'W_309', 'texto': 'Puesto que', 'nivel': 5, 'fonema': 'p', 'cat': 10, 'dif': 'alta', 'img': 'puesto_que', 'tags': []},
    {'id': 'W_310', 'texto': 'Empatía', 'nivel': 5, 'fonema': 'm', 'cat': 11, 'dif': 'alta', 'img': 'empatía', 'tags': []},
    {'id': 'W_311', 'texto': 'Resiliencia', 'nivel': 5, 'fonema': 'l', 'cat': 12, 'dif': 'alta', 'img': 'resiliencia', 'tags': []},
    {'id': 'W_312', 'texto': 'Paradigma', 'nivel': 5, 'fonema': 'r', 'cat': 1, 'dif': 'alta', 'img': 'paradigma', 'tags': []},
    {'id': 'W_313', 'texto': 'Inferencia', 'nivel': 5, 'fonema': 'n', 'cat': 2, 'dif': 'alta', 'img': 'inferencia', 'tags': []},
    {'id': 'W_314', 'texto': 'Pragmática', 'nivel': 5, 'fonema': 'm', 'cat': 3, 'dif': 'alta', 'img': 'pragmática', 'tags': []},
    {'id': 'W_315', 'texto': 'Semántica', 'nivel': 5, 'fonema': 'm', 'cat': 4, 'dif': 'alta', 'img': 'semántica', 'tags': []},
    {'id': 'W_316', 'texto': 'Sintaxis', 'nivel': 5, 'fonema': 't', 'cat': 5, 'dif': 'alta', 'img': 'sintaxis', 'tags': []},
]

_IMG_KEYWORDS: dict[str, str] = {
    # Nivel 1 – palabras simples
    'perro': 'dog', 'gato': 'cat', 'vaca': 'cow', 'pato': 'duck',
    'pez': 'fish', 'mano': 'hand', 'pie': 'foot', 'mamá': 'mother+child',
    'papá': 'father+child', 'cama': 'bed', 'silla': 'chair', 'pan': 'bread',
    'leche': 'milk', 'agua': 'water+glass', 'oso': 'bear', 'sapo': 'frog',
    'bebé': 'baby', 'dedo': 'finger', 'boca': 'mouth', 'ojo': 'eye',
    'mesa': 'table', 'puerta': 'door', 'duna': 'sand+dune', 'pelo': 'hair',
    'nube': 'cloud', 'tío': 'uncle', 'tía': 'aunt',
    'abuelo': 'grandfather', 'abuela': 'grandmother',
    'diente': 'tooth', 'nariz': 'nose', 'pelota': 'ball',
    'cubo': 'toy+block', 'tren': 'train', 'sol': 'sun',
    'luna': 'moon', 'flor': 'flower', 'uva': 'grapes', 'pera': 'pear',
    'maíz': 'corn', 'sopa': 'soup', 'huevo': 'egg', 'casa': 'house',
    'vaso': 'glass+water', 'bota': 'boot', 'caja': 'box',
    'dama': 'lady', 'pino': 'pine+tree', 'tapa': 'lid',
    'mapa': 'map', 'lupa': 'magnifying+glass', 'puma': 'puma+animal',
    'moto': 'motorcycle', 'nene': 'toddler',
    # Nivel 2
    'conejo': 'rabbit', 'tortuga': 'turtle', 'jirafa': 'giraffe',
    'elefante': 'elephant', 'mariposa': 'butterfly', 'naranja': 'orange+fruit',
    'sandía': 'watermelon', 'queso': 'cheese', 'pollo': 'chicken',
    'arroz': 'rice', 'camisa': 'shirt', 'pantalón': 'pants',
    'azul': 'blue+color+paint', 'rojo': 'red+color+paint',
    'verde': 'green+color+paint',
    'correr': 'running+child', 'saltar': 'jumping+child',
    'comer': 'eating+child', 'dormir': 'sleeping+child',
    'escuela': 'school', 'parque': 'playground', 'tienda': 'store',
    'bicicleta': 'bicycle', 'avión': 'airplane', 'barco': 'boat',
    'zapato': 'shoe', 'calcetín': 'sock', 'sombrero': 'hat',
    'guante': 'glove', 'falda': 'skirt', 'abrigo': 'coat',
    'bufanda': 'scarf', 'pijama': 'pajamas', 'yogur': 'yogurt',
    'helado': 'ice+cream', 'galleta': 'cookie', 'fresa': 'strawberry',
    'círculo': 'circle+shape', 'cuadrado': 'square+shape',
    'triángulo': 'triangle+shape',
    'grande': 'big+elephant', 'pequeño': 'small+ant',
    'bailar': 'dancing+child', 'cantar': 'singing+child',
    'nadar': 'swimming+child', 'reír': 'laughing+child',
    'llorar': 'crying+child', 'jugar': 'playing+child',
    'jardín': 'garden', 'cocina': 'kitchen', 'baño': 'bathroom',
    'camión': 'truck', 'limón': 'lemon', 'fuego': 'fire',
    'llave': 'key', 'nido': 'bird+nest', 'foca': 'seal+animal',
    'gallo': 'rooster', 'hormiga': 'ant', 'gallina': 'hen',
    'caballo': 'horse', 'loro': 'parrot', 'rana': 'frog+green',
    # Nivel 3
    'dragón': 'dragon+illustration', 'cocodrilo': 'crocodile',
    'flamenco': 'flamingo', 'grillo': 'cricket+insect',
    'delfín': 'dolphin', 'tigre': 'tiger',
    'árbol': 'tree', 'piedra': 'rock+stone', 'trueno': 'thunder+lightning',
    'playa': 'beach', 'bosque': 'forest', 'volcán': 'volcano',
    'estrella': 'star+sky', 'helicóptero': 'helicopter',
    'grúa': 'crane+machine', 'tractór': 'tractor',
    'submarino': 'submarine', 'trineo': 'sled+snow',
    'patín': 'roller+skate', 'trepar': 'climbing+child',
    'gritar': 'shouting+child', 'frotar': 'rubbing+hands',
    'abrazar': 'hugging', 'dibujar': 'drawing+child',
    'construir': 'building+blocks', 'plantar': 'planting+seed',
    'preparar': 'cooking+preparation', 'explorar': 'exploring+child',
    'trabajar': 'working', 'escribir': 'writing',
    'limpiar': 'cleaning', 'feliz': 'happy+child',
    'triste': 'sad+child', 'enojado': 'angry+child',
    'asustado': 'scared+child', 'sorprendido': 'surprised+child',
    'aburrido': 'bored+child',
    'doctor': 'doctor', 'bombero': 'firefighter',
    'maestro': 'teacher+classroom', 'cocinero': 'chef+cooking',
    'policía': 'police+officer',
    'rápido': 'fast+cheetah', 'lento': 'slow+snail',
    'suave': 'soft+cotton', 'rugoso': 'rough+texture',
    'brillante': 'shiny+diamond',
    'ventana': 'window', 'escalera': 'stairs',
    'techo': 'roof', 'garaje': 'garage',
    'sótano': 'basement', 'balcón': 'balcony',
    'planeta': 'planet', 'cometa': 'comet+space',
    'princesa': 'princess', 'príncipe': 'prince',
    'globo': 'balloon', 'plato': 'plate',
    'blusa': 'blouse', 'clavo': 'nail+metal',
    'flauta': 'flute', 'fruta': 'fruit',
    'gruta': 'cave+grotto', 'pluma': 'feather',
    'brazo': 'arm', 'crema': 'cream+jar',
    'freno': 'brake', 'grano': 'grain+wheat',
    'presa': 'dam+water', 'trigo': 'wheat+field',
    'clima': 'weather', 'flecha': 'arrow',
    'plomo': 'lead+metal', 'canguro': 'kangaroo',
    # Nivel 4
    'frustración': 'frustrated+child', 'entusiasmo': 'excited+child',
    'nostalgia': 'nostalgia+memory', 'decepción': 'disappointed+child',
    'gratitud': 'grateful+thank+you', 'valentía': 'brave+courage',
    'vergüenza': 'embarrassed+child', 'envidia': 'envy+jealousy',
    'confianza': 'confidence', 'soledad': 'loneliness',
    'gravedad': 'gravity+apple', 'evaporación': 'evaporation+water',
    'fotosíntesis': 'photosynthesis+plant', 'eclipse': 'eclipse+sun',
    'terremoto': 'earthquake', 'atmósfera': 'atmosphere+earth',
    'cristal': 'crystal', 'imán': 'magnet',
    'energía': 'energy+lightning', 'oxígeno': 'oxygen+bubbles',
    'ecosistema': 'ecosystem+nature',
    'arqueólogo': 'archaeologist', 'astronauta': 'astronaut',
    'veterinario': 'veterinarian', 'científico': 'scientist',
    'arquitecto': 'architect', 'periodista': 'journalist',
    'programador': 'programmer+coding', 'atleta': 'athlete',
    'músico': 'musician', 'filósofo': 'philosopher',
    'imaginar': 'imagination+lightbulb', 'resolver': 'solving+puzzle',
    'comparar': 'comparing', 'describir': 'describing',
    'analizar': 'analyzing+magnifying', 'recordar': 'memory+brain',
    'predecir': 'prediction+fortune', 'reflexionar': 'thinking+child',
    'organizar': 'organizing', 'opinar': 'opinion+speech',
    'continente': 'continent+map', 'desierto': 'desert',
    'selva': 'jungle', 'polo': 'arctic+pole',
    'océano': 'ocean', 'ciudad': 'city',
    'aldea': 'village', 'frontera': 'border+fence',
    'capital': 'capital+city', 'archipiélago': 'archipelago+islands',
    'ayer': 'yesterday+calendar', 'mañana': 'tomorrow+sunrise',
    'siempre': 'infinity+forever', 'nunca': 'never+stop+sign',
    'mientras': 'hourglass+time', 'durante': 'during+clock',
    'después': 'after+clock', 'antes': 'before+clock',
    'relatividad': 'relativity+physics', 'genética': 'genetics+dna',
    # Nivel 5
    'justicia': 'justice+scales', 'libertad': 'freedom+statue',
    'democracia': 'democracy+voting', 'responsabilidad': 'responsibility',
    'creatividad': 'creativity+art', 'solidaridad': 'solidarity+helping',
    'ética': 'ethics+philosophy', 'tolerancia': 'tolerance+diversity',
    'identidad': 'identity+mirror', 'cultura': 'culture+diversity',
    'evolución': 'evolution+darwin', 'perspectiva': 'perspective+view',
    'hipótesis': 'hypothesis+science', 'evidencia': 'evidence+clue',
    'argumento': 'argument+debate', 'conclusión': 'conclusion+checkmark',
    'síntesis': 'synthesis+science', 'metáfora': 'metaphor+poetry',
    'protagonista': 'protagonist+hero', 'antagonista': 'antagonist+villain',
    'narrador': 'narrator+storytelling', 'rima': 'rhyme+poetry',
    'estrofa': 'stanza+poem', 'párrafo': 'paragraph+text',
    'deducir': 'detective+deduction', 'inferir': 'inference+thinking',
    'sintetizar': 'summarize+notes', 'contextualizar': 'context+puzzle',
    'argumentar': 'debate+argument', 'evaluar': 'evaluation+checklist',
    'debatir': 'debate+people', 'contrastar': 'contrast+comparison',
    'justificar': 'justify+reasoning', 'hipotetizar': 'hypothesis+lightbulb',
    'clasificar': 'classify+sorting', 'formular': 'formula+science',
    'lloviendo_a_cántaros': 'heavy+rain', 'ojo_de_la_cara': 'expensive+diamond',
    'pez_gordo': 'important+boss', 'mano_izquierda': 'diplomacy+handshake',
    'pisar_el_acelerador': 'speeding+car',
    'romper_el_hielo': 'icebreaker+conversation',
    'tirar_la_toalla': 'giving+up', 'sin_embargo': 'however+contrast',
    'por_lo_tanto': 'therefore+arrow', 'a_pesar_de': 'despite+obstacle',
    'consecuencia': 'consequence+domino', 'no_obstante': 'nevertheless',
    'es_decir': 'meaning+explanation', 'en_resumen': 'summary+notes',
    'asimismo': 'likewise+equals', 'aunque': 'although+but',
    'puesto_que': 'because+reason',
    'empatía': 'empathy+caring', 'resiliencia': 'resilience+growth',
    'paradigma': 'paradigm+shift', 'inferencia': 'inference+detective',
    'pragmática': 'pragmatic+practical', 'semántica': 'semantics+words',
    'sintaxis': 'syntax+grammar',
}


import urllib.request
import urllib.parse
import json

async def fetch_wiki_image(sem: asyncio.Semaphore, word: str) -> str:
    async with sem:
        # Search for the main concept on Spanish Wikipedia
        url = f"https://es.wikipedia.org/api/rest_v1/page/summary/{urllib.parse.quote(word)}"
        try:
            def _fetch():
                req = urllib.request.Request(url, headers={'User-Agent': 'Appfasia-Seeder/1.0'})
                with urllib.request.urlopen(req, timeout=3) as response:
                    return json.loads(response.read().decode())
            data = await asyncio.to_thread(_fetch)
            if 'originalimage' in data and 'source' in data['originalimage']:
                return data['originalimage']['source']
        except Exception:
            pass
        return f"https://placehold.co/512x512?text={urllib.parse.quote(word)}"


async def seed_postgres():
    database_url = os.getenv("DATABASE_URL", "postgresql://appfasia_user:-Admin07-@localhost:5432/appfasia")
    # Forzamos la conexión local por defecto asumiendo que se corre desde la máquina host y el puerto está mapeado
    print(f"[*] Conectando a PostgreSQL: {database_url}")
    
    try:
        conn = await asyncpg.connect(database_url)
    except Exception as e:
        print(f"[!] Error de conexión: {e}")
        return

    print("[*] Buscando imágenes representativas en Wikipedia de forma concurrente...")
    sem = asyncio.Semaphore(15)
    tasks = [fetch_wiki_image(sem, r['texto']) for r in RECURSOS_SEED]
    image_urls = await asyncio.gather(*tasks)

    print("[*] Insertando recursos en base de datos...")
    
    # Limpiamos antes para que sea idempotente
    await conn.execute("DELETE FROM resultados_ejercicio")
    await conn.execute("DELETE FROM recursos")

    inserted = 0
    for r, imagen_url in zip(RECURSOS_SEED, image_urls):
        # URL ficticia para audios por ahora
        audio_url = f"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
        
        try:
            await conn.execute('''
                INSERT INTO recursos (
                    id_recurso, tipo, texto, nivel_sugerido, fonema_objetivo, 
                    id_categoria, dificultad_art, imagen_url, audio_url, tags
                ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
            ''', r["id"], "palabra", r["texto"], r["nivel"], r["fonema"], 
                 r["cat"], r["dif"], imagen_url, audio_url, r["tags"])
            inserted += 1
        except Exception as e:
            print(f"[!] Error insertando {r['id']}: {e}")

    await conn.close()
    print(f"[+] Seeding completado. {inserted} recursos insertados en PostgreSQL.")

if __name__ == "__main__":
    asyncio.run(seed_postgres())

